const EVENT_MESSAGE_CSS = {
    JOIN_ROOM_CSS: 'JOIN_ROOM_CSS',
    LEAVE_ROOM_CSS: 'LEAVE_ROOM_CSS',
    SEND_MESSAGE_CSS: 'SEND_MESSAGE_CSS',
    UPDATE_MESSAGE_CSS: 'UPDATE_MESSAGE_CSS',
    REMOVE_MESSAGE_CSS: 'REMOVE_MESSAGE_CSS',
};

module.exports = EVENT_MESSAGE_CSS;
