const EVENT_MESSAGE_SSC = {
    JOIN_ROOM_SSC: 'JOIN_ROOM_SSC',
    LEAVE_ROOM_SSC: 'LEAVE_ROOM_SSC',
    SEND_MESSAGE_SSC: 'SEND_MESSAGE_SSC',
    UPDATE_MESSAGE_SSC: 'UPDATE_MESSAGE_SSC',
    REMOVE_MESSAGE_SSC: 'REMOVE_MESSAGE_SSC',
};

module.exports = EVENT_MESSAGE_SSC;
